name: Main

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Unit tests
    uses: ./.github/workflows/unit_tests.yml
    with:
      linux_5_8_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      linux_5_9_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      linux_5_10_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      linux_nightly_6_0_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      linux_nightly_main_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"

  benchmarks:
    name: Benchmarks
    uses: ./.github/workflows/benchmarks.yml
    with:
      benchmark_package_path: "Benchmarks"

  cxx-interop:
    name: Cxx interop
    uses: ./.github/workflows/cxx_interop.yml
